#ifndef VERSION_H
#define VERSION_H
//Include the current git createn version output!
//#include "gitversion.h"

#define VER_FILEVERSION             1,0,0,0
#define VER_FILEVERSION_STR         GITVERSION

#define VER_PRODUCTVERSION          1,0,0,0
#define VER_PRODUCTVERSION_STR      VER_FILEVERSION_STR

#define VER_COMPANYNAME_STR         COMPANYNAME
#define VER_FILEDESCRIPTION_STR     PRODUCTNAME
#define VER_INTERNALNAME_STR        PRODUCTNAME
#define VER_LEGALCOPYRIGHT_STR      ""
#define VER_LEGALTRADEMARKS1_STR    ""
#define VER_LEGALTRADEMARKS2_STR    VER_LEGALTRADEMARKS1_STR
#define VER_ORIGINALFILENAME_STR    ORIGINALFILENAME
#define VER_PRODUCTNAME_STR         PRODUCTNAME

#define VER_COMPANYDOMAIN_STR       ""

#endif // VERSION_H
